lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Ścieżka do klucza prywatnego
    public_key: '%kernel.project_dir%/config/jwt/public.pem'   # Ścieżka do klucza publicznego
    pass_phrase: '123123'                                   # Hasło do klucza
    token_ttl: 3600                                             # Czas ważności tokena w sekundach